export const ADD_INGRIDENT = 'ADD_INGRIDENT';
export const REMOVE_INGRIDENT = 'REMOVE_INGRIDENT';
export const STORE_INGRIDENT ='STORE_INGRIDENT';
export const SIGN_UP ='SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const LOGOUT = 'LOGOUT';
export const INITIAL_STATE='INITIAL_STATE';
